# 诊断用 spec：console=True 捕获报错，构建为 L.NoteDebug.exe
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('dist-web/index.html', '.'),
        ('compare.html', '.'),
        ('image_viewer.html', '.'),
        ('dist-web/assets', 'assets'),
        ('dist-web/js', 'js'),
        ('dist-web/vendor', 'vendor'),
        ('css', 'css'),
        ('icons', 'icons'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='L.NoteDebug',
    icon='icons/L.NOTE/icon-L.NOTE.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)